name: happy_view
description: A Flutter app for kids to view pictures without parents concern.
publish_to: 'Nawras Al Abbas'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.5
  firebase_core: ^3.12.1
  http: ^1.3.0 # For making HTTP requests
  cached_network_image: ^3.3.1 
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  permission_handler: ^11.4.0
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  gal: ^2.3.1 
  image: ^4.5.4 
  flutter_cache_manager: ^3.3.1
  url_launcher: ^6.3.1
  firebase_analytics: ^11.4.4
  flutter_spinkit: ^5.2.1
  audioplayers: ^6.4.0
  translator: ^1.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.5
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/assets/images/
    - lib/l10n/
    - assets/sounds/yay.wav
    - assets/profanity/en.json
   
